name: Connect to Salesforce
description: Authenticates to the Salesforce DevHub

inputs:
  sfdx_auth_url:
    description: SFDX url to use when authenticating to the org
    required: true

runs:
  using: 'composite'
  steps:
    - name: Connect to Salesforce
      run: |
        echo ${{ inputs.sfdx_auth_url }} > sfdxurlfile.txt
        sfdx auth:sfdxurl:store \
          --setalias=brettbarlow-dev-ed-ci \
          --setdefaultusername \
          --setdefaultdevhubusername \
          --sfdxurlfile=sfdxurlfile.txt
      shell: bash
