name: 'Install SFDX'
description: 'Installs and caches SFDX'

runs:
  using: 'composite'
  steps:
    - name: Install SFDX
      if: steps.cache-sfdx.outputs.cache-hit != 'true'
      run: |
        npm install sfdx-cli --global
        npm install @salesforce/cli --global
        echo ""
        echo "Installed SFDX with version:"
        sfdx --version
      shell: bash
