name: 'Prepare'
description: 'Installs Node, SFDX and builds project dependencies'

runs:
  using: 'composite'
  steps:
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install SFDX
      run: |
        npm install sfdx-cli --global
        npm install @salesforce/cli --global
      shell: bash

    - name: Build Dependencies
      run: npm ci
      shell: bash
