name: 'Prepare'
description: 'Installs Node, SFDX and project dependencies'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: |
        npm install sfdx-cli --global
        npm install @salesforce/cli --global
      shell: bash
    - run: npm ci
      shell: bash
