name: Check Format

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-format:
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Check formatting
        run: |
          npm run check:apex
          npm run check:apex:scripts
          npm run check:apex:lwc
          npm run check:apex:other
