name: Pull Request

on:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - name: Check Formatting
        run: |
          npm run check:apex
          npm run check:apex:scripts
          npm run check:lwc
          npm run check:other

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - name: Install SF Scanner
        run: sfdx plugins:install @salesforce/sfdx-scanner@latest-pilot
      - name: Lint
        run: |
          npm run lint:apex
          npm run lint:lwc

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - name: Test
        run: npm run test:lwc

  validate-in-salesforce:
    needs: [check-formatting, lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - name: Connect to Salesforce
        uses: ./.github/actions/connect-to-salesforce
      - name: Validate in Salesforce
        run: npm run sf:validate
