name: Pull Request

on:
  pull_request:

jobs:
  # prepare:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Install NPM
  #       uses: ./.github/actions/install-npm
  #     - name: Install SFDX
  #       uses: ./.github/actions/install-sfdx

  check-formatting:
    runs-on: ubuntu-latest
    # needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NPM
        uses: ./.github/actions/install-npm
      - name: Check Formatting
        run: |
          npm run check:apex
          npm run check:apex:scripts
          npm run check:lwc
          npm run check:other

  lint:
    runs-on: ubuntu-latest
    # needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NPM
        uses: ./.github/actions/install-npm
      - name: Lint
        run: |
          npm run lint:apex
          npm run lint:lwc

  test:
    runs-on: ubuntu-latest
    # needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NPM
        uses: ./.github/actions/install-npm
      - name: Test
        run: npm run test:lwc

  connect-to-salesforce:
    needs: [check-formatting, lint, test]
    uses: ./.github/workflows/connect-to-salesforce.yml
    secrets:
      sfdx_auth_url: ${{ secrets.SFDX_AUTH_URL }}

  validate-in-salesforce:
    runs-on: ubuntu-latest
    needs: connect-to-salesforce
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate in Salesforce
        run: npm run sf:validate
