name: Pull Request

on:
  pull_request:

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NPM
        uses: ./.github/actions/install-npm
      - name: Check Formatting
        run: |
          npm run check:apex
          npm run check:apex:scripts
          npm run check:lwc
          npm run check:other

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install SFDX
        uses: ./.github/actions/install-sfdx
      - name: Install SF Scanner
        run: |
          sfdx/bin/sfdx version
          sfdx/bin/sfdx plugins:install @salesforce/sfdx-scanner@latest-pilot
      - name: Lint
        run: |
          npm run lint:apex
          npm run lint:lwc

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NPM
        uses: ./.github/actions/install-npm
      - name: Test
        run: npm run test:lwc

  validate-in-salesforce:
    needs: [check-formatting, lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install SFDX
        uses: ./.github/actions/install-sfdx
      - name: Connect to Salesforce
        uses: ./.github/actions/connect-to-salesforce
      - name: Validate in Salesforce
        run: npm run sf:validate
