name: Salesforce Scratch Org

on:
  workflow_dispatch:
  schedule:
    - cron: '30 11 * * *' # 11:30 UTC == 04:30 PT

env:
  SCRATCH_ORG_ALIAS: brettbarlow-scratch

jobs:
  make-scratch-org:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Connect to Salesforce
        uses: ./.github/actions/connect-to-salesforce

      - name: Make Scratch Org
        run: ./scripts/make_scratch_org.sh

      - name: Delete Scratch Org
        if: always()
        run: |
          sfdx force:org:delete \
            --noprompt \
            --targetusername="$SCRATCH_ORG_ALIAS"
